### ISSUE TITLE
What are these training file look like?

### ISSUE THREAD

**Issue by ghost** [thunlp/SE-WRL#1]
Hi, I am a tyro of the area. And I am sorry that can't understand the README clearly. Could you submit some examples of your training files,  I can't figure out what are these 4 training file look like? Thank you~

**Comment by heyLinsir** [comment]
We will upload all the training files recently except the TrainFile. TrainFile is too large(21G). If the upload size is suitable, we will also upload the result embeddings.

**Comment by Lee-zix** [comment]
In the description of your dataset, it show " The average senses for each word are about 2.4", but in your 'Word_Sense_Sememe_File', there are 4652 words have more than one sense among 462667 words, how the number 2.4 is statisticsed??  
    In the 4.5.2 part of your paper, it show word 'Havana' has one sense and the the sense consists of 4 senses, the paper show the different context words have different attention on different sememes. But in your algorithm, the attention is on the senses but not the sememes(simplely using the average of sememes to represent the sense and using the sense embeddings to represent the word if the word has only one sense ), is there some misunderstanding about the case ??
  Thanks for your reply!

**Comment by lidra** [comment]
Hi, Could you upload the result embeddings or give a link such as in BaiduYun where I can load the result embeddings. Thank you very much.

**Comment by heyLinsir** [comment]
Ok, I can do this. But maybe I have lost these embedding files. So I need to train them once again. Can you wait for some days?

**Comment by lidra** [comment]
Of course it is ok, thank you very much.

**Comment by heyLinsir** [comment]
https://pan.baidu.com/s/1c2524b2
pw:5frt
Because of time limitted, the embedding of this version can't achieve the best performance. I will replace it with another version in some days.

**Comment by lidra** [comment]
多谢多谢，还有一个问题，这个模型是用中文的HOWNET训练得到词向量的，那么有没有办法扩展到英文应用上呢。

**Comment by heyLinsir** [comment]
我们组已经在做这方面的探索，欢迎继续关注。
