### ISSUE TITLE
一个word包含哪些sense和sememe是怎么确定的呢

### ISSUE THREAD

**Issue by saber1988** [thunlp/SE-WRL#10]
请教一下，研究paper之后没有找到具体确定一个word包含哪些sense和sememe的方式，看逻辑好像是先有了这些信息，再取对应的word、sense、sememe embedding进行学习，不知道我理解的对不对。
很棒的paper，非常感谢。

**Comment by heyLinsir** [comment]
@saber1988 sense和sememe的信息由HowNet提供，可以直接通过这个知识库获取。

**Comment by saber1988** [comment]
好的，非常感谢啦
