### ISSUE TITLE
所有词都在hownet上么

### ISSUE THREAD

**Issue by maozida880** [thunlp/SE-WRL#12]
每个词都有多个义意S，每个义意又有多个义源X
hownet比较有限，不没有把所有词都标记了C(X)
那么没标记的词怎么处理的？

**Comment by heyLinsir** [comment]
没有标记的词当作单义词处理，不考虑义原信息。
即，只考虑单一的词向量信息，认为该词只有一个sense，不过这个sense只有自己的向量表示，没有对应的义原。
