### ISSUE TITLE
data process

### ISSUE THREAD

**Issue by gqh1995** [thunlp/SE-WRL#13]
您好！
我在follow您的工作的过程中遇到了一些问题。
在复现了您的所有工作以后，我考虑使用其他的语料进行词向量的训练。在处理好语料集和vocab文件之后，接着生成自己的Word_Sense_Sememe_File时遇到了困难。
1.首先我在您的提供的代码中找到了data process的代码，在运行后得到的是空文件，自己仔细研读之后发现代码可能是不完整的，我猜想是缺少了sense级的处理和整个的循环部分，请问是这样吗？如果确实不完整请您告知我，我自己对这部分进行coding，此外假如您可以提供这部分的完整代码，方便我接下来的研究，则感激不尽！
2.您提供的Word_Sense_Sememe_File是否包含了hownet的所有词？我是否可以直接使用您提供Word_Sense_Sememe_File做对齐？
期望您的答复，谢谢！

**Comment by heyLinsir** [comment]
1. 您不需要生成自己的Word_Sense_Sememe_File，这个文件是通用的，它是直接从HowNet中抽取得到，一般来讲足以覆盖新的语料。
2. 可以直接使用我提供的Word_Sense_Sememe_File做对齐，它包含了HowNet中的所有词。

**Comment by gqh1995** [comment]
谢谢解答！

**Comment by ghost** [comment]
您好，我不知道是不是我理解有误：
Word_Sense_Sememe_File 文件中，有一些我无法理解的现象，比如第12行的
“也 1”
“也”字可以理解为词，但是后面紧跟着的数字“1”怎么解释呢？
我发现 Word_Sense_Sememe_File 文件后面存在很多这样的情况——一个词后面跟着一个数字1——这应该怎么理解？

**Comment by gqh1995** [comment]
表示在hownet里没有对这个词的解释，只有一个词，没有对应的sense和sememe，所以标1

**Comment by ghost** [comment]
谢谢指教！

**Comment by ghost** [comment]
如果“在hownet里没有对这个词的解释”，那么 SE-WRL 模型应该怎么训练这个词的 embedding 呢？

**Comment by heyLinsir** [comment]
模型随机初始化这个词的embedding，每次预测这个单词的出现概率的时候，都会用这个embedding作为在当前上下文环境下的词表示。因为我们认为这个单词只有一个含义，所以词表示不会随着上下文变化而改变。训练过程和skip-gram类似。

**Comment by ghost** [comment]
谢谢您耐心的解答！

**Comment by MathewLi9527** [comment]
建议加一个文件格式说明的文件。
