### ISSUE TITLE
训练和评估问题

### ISSUE THREAD

**Issue by embraceth** [thunlp/SE-WRL#17]
您好！我是词向量方面的一个新手，所以有两个问题需要问您一下：
1.make
./word2vec -train TrainFile -output vectors.bin -cbow 0 -size 200 -window 8 。。。中的TrainFile是指datasets中的Hownet.txt或者sougou-T（sample）.txt吗？
2.训练出来的vector.bin，是怎么样做word analogy和word similarity评估的，有给代码吗？或者在哪能有这**些资料。
非常感谢！

**Comment by heyLinsir** [comment]
1. TrainFile是指sougou-T，你可以从网盘下载数据，网盘链接在README中。
2. 关于vector.bin的格式，可以参考https://github.com/thunlp/SE-WRL/issues/11。评估脚本可以参考https://github.com/thunlp/SE-WRL/issues/8。

**Comment by embraceth** [comment]
ok，谢谢您！
