### ISSUE TITLE
训练结果

### ISSUE THREAD

**Issue by marx12345** [thunlp/SE-WRL#18]
你好，我想利用下你们的训练的词向量做一下中文处理的下游任务，试试效果如何，不知道能否提供。

**Comment by Fanchao-Qi** [comment]
@marx12345 你好，在SAT模型的[新repo](https://github.com/thunlp/SE-WRL-SAT)的readme中有词向量的下载地址：https://cloud.tsinghua.edu.cn/d/c8c4a35065ee4b50a132/
