### ISSUE TITLE
two questions about the paper

### ISSUE THREAD

**Issue by Lee-zix** [thunlp/SE-WRL#2]
In the description of your dataset, it show " The average senses for each word are about 2.4", but in your 'Word_Sense_Sememe_File', there are 4652 words have more than one sense among 462667 words, how the number 2.4 is statisticsed??
In the 4.5.2 part of your paper, it show word 'Havana' has one sense and the the sense consists of 4 senses, the paper show the different context words have different attention on different sememes. But in your algorithm, the attention is on the senses but not the sememes(simplely using the average of sememes to represent the sense and using the sense embeddings to represent the word if the word has only one sense ), is there some misunderstanding about the case ??
Thanks for your reply!

**Comment by heyLinsir** [comment]
Thanks for your questions!
1. The number of average senses is statisticsed on words with more than one sense. 
2. In the 4.5.2 part of paper, I just want to show each sememe's influence on attention. Attention is calculated using sememe embeddings and word embeddings, while used on senses. 4.5.2 part shows the similarity of sememes and words. It is not included in training process.
Are your questions solved?

**Comment by Lee-zix** [comment]
I got it! Thank you very much for your reply!
