### ISSUE TITLE
how to get the "HowNet.txt"

### ISSUE THREAD

**Issue by XingLuxi** [thunlp/SE-WRL#20]
how to extract the HowNet.txt/SememeFile/Word_Sense_Sememe_File from the original Hownet data?

**Comment by heyLinsir** [comment]
HowNet.txt is from another researcher.
SememeFile contains all sememes from HowNet.txt.
Word_Sense_Sememe_File finds all senses for each word in HowNet.txt. One item in HowNet.txt corresponds to one sense of a word.

**Comment by XingLuxi** [comment]
Thanks！
