### ISSUE TITLE
VocabFile problem

### ISSUE THREAD

**Issue by bestpredicts** [thunlp/SE-WRL#22]
Hi, when  I add a  word like '蛤蛤  50'  to  VocabFile ,   then  I  train model , but  I get  a  error 
  
`dy@ubun:~/SE-WRL-master/datasets$ ./word2vec -train Clean-Sogou-ALL.txt  -output vectors.bin -cbow 0 -size 200 -window 8 -negative 25 -hs 0 -sample 1e-4 -thre
ads 30 -binary 1 -iter 3 -read-vocab VocabFile  -read-meaning SememeFile -read-sense Word_Sense_Sememe_File -min-count 50 -alpha 0.025  
Starting training using file Clean-Sogou-ALL.txt   
Vocab size: 462667  
Words in train file: 2655924607  
462667  
1983  
Alpha: 0.024999  Progress: 0.00%  Words/thread/sec: 1.83k  Segmentation fault`
how can  I add words to  VocabFile ?

**Comment by heyLinsir** [comment]
If you add new words to VocabFile, these words should be also added to Word_Sense_Sememe_File.
