### ISSUE TITLE
词义消歧

### ISSUE THREAD

**Issue by xiaopp123** [thunlp/SE-WRL#24]
您好，在论文里有提到词义消歧，具体的消歧过程是怎样的，是否可以提供demo?

**Comment by heyLinsir** [comment]
我们的论文主要想体现的是，通过进行soft的词义消歧获得词向量的提升，具体做法是使用attention机制为目标单词的每一个语义赋予一个权值，可以认为，权值较大的更有可能是符合当前语境的语义。因为消歧不是该方法的重点，所以暂时没有demo，只是想说明有消歧的潜力。

**Comment by xiaopp123** [comment]
请问目标词的每一个词义是怎么获取的呢？

**Comment by heyLinsir** [comment]
词义都是从HowNet中提取出来的，每个单词有多少种解释就认为有多少种词义，每种词义都用义原进行描述。
