### ISSUE TITLE
word_vec的作用

### ISSUE THREAD

**Issue by liuyijiang1994** [thunlp/SE-WRL#25]
您好，阅读您的代码后，想请问每一个词语的vec的作用仅仅是提供上下文向量嘛？
还是说有其他的地方使用了word_vec？

**Comment by liuyijiang1994** [comment]
啊忘了说明 是在SAT这部分中

**Comment by heyLinsir** [comment]
在SAT中是这样的，只有上下文单词使用到了word vector；中心词只使用了sememe vector和sense vector。

**Comment by liuyijiang1994** [comment]
非常感谢您及时的解答！
