### ISSUE TITLE
语料库

### ISSUE THREAD

**Issue by embraceth** [thunlp/SE-WRL#28]
您好，我想使用自己的语料库去训练您的模型，所以您的模型对于语料库的要求是啥，简单分词即可吗？我看到您提供的train_sample.txt里面：
据 新华社 伊斯兰堡 1月 <date> 电 （ 记者 许 <unk> ） 巴基斯坦 外交部 今天 宣布 ， 由于 美国 方面 至今 既 不 交付 巴 方 已 订购 的 <unk> <unk> ， 又 不 退还 <unk> <unk> ， 巴 政府 计划 就 此 事 上诉 美国 法院 。
随着 各国 人民 之间 交往 的 增多 ， 他们的 文化 、 风俗 、 习惯 等等 也 都 在 相互 传播 ， 相互 吸收 ， 这 应该 说 是 <N> 件 好事 
不是简单的分词，这地方的<unk>,<data><N>分别表示什么？

**Comment by heyLinsir** [comment]
语料库没有特殊的要求，只需要进行分词。我们使用的是THULAC分词工具。
