### ISSUE TITLE
请问只有一个sense的词的sememe id怎么得到？

### ISSUE THREAD

**Issue by lbe0613** [thunlp/SE-WRL#31]
Word_Sense_Sememe_File里面只有一个sense的词没有标注对应的sememe，请问可以得到吗？

**Comment by yangalan123** [comment]
您好，非常抱歉回复晚了，HowNet中确实是存在着一些词只标注了第一层的义原（即本文的sense），我们的工作直接利用的当时的HowNet文件版本。为了获取最新的HowNet数据以及API，请关注我们开源的OpenHowNet工具包：https://github.com/thunlp/OpenHowNet
