### ISSUE TITLE
模型应用

### ISSUE THREAD

**Issue by xudekuan** [thunlp/SE-WRL#32]
请问两个关于模型的应用问题：

1.模型训练好之后，是否可以用于wsd？就是，输入普通文本，输出wsd后的文本？
 2.模型训练好之后，是否可以用于预测义原，即，输入普通文本，输出义原的序列？

非常感谢！

**Comment by yangalan123** [comment]
1. 您好，我们在这篇工作中仅通过case study的方式展示我们的工作在WSD的潜在应用（详情可以参考paper的4.5.1节），目前没有严格测试是否可以直接应用在WSD上。
2. 这是一个非常好的问题，我们的模型将会同时训练义原和词的表示，它们有可能能为义原预测的有关工作提供有益的输入，您可以尝试利用我们在https://github.com/thunlp/SE-WRL-SAT 开源的词向量和义原向量进行有关的尝试，我们欢迎您在此与我们交流您的观察与发现！

**Comment by xudekuan** [comment]
非常感谢您的回答。我目前正在复现您的代码，发现，每运行一次，结果都不一样。

**Comment by yangalan123** [comment]
我们的代码是预先固定随机种子的，应该跑多少次重复实验都有相同的结果，您是使用自己复现的代码还是使用我们的代码？如果使用自己复现的代码，请检查您是否固定了随机种子--模型训练过程中需要进行负采样，如果不固定随机数种子，那么就会多次跑出来的结果都不太一样

**Comment by xudekuan** [comment]
我用的是这个链接里的代码 https://github.com/thunlp/SE-WRL-SAT

**Comment by xudekuan** [comment]
| WordSim-240 Score | WordSim-297 Score
重新第一次 | 0.6216854959448419 | 0.6278795368801042
重新第二次 | 0.6217434132985868 | 0.635456621032264
重新第三次 | 0.6238719078684416 | 0.6280517586441791
