### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by quan3401** [thunlp/SE-WRL#4]
您好，我这边在Windows跑您的代码，Starting training using file E:\C++Code\Word2Vector\datasets\Sougo-T(sample).txt
Vocab size: 462667
Words in train file: 2655924606
462667
1983
success load data
success InitNet
success InitUnigramTable
start train

在训练的时候，// BP
		g /= total;			
total存在等于0的情况，参数是readme 设置的。麻烦帮忙解答一下，谢谢。

**Comment by heyLinsir** [comment]
请问还有问题吗？抱歉之前没有收到邮件提醒，只收到了关闭问题的提醒。
