### ISSUE TITLE
help ！

### ISSUE THREAD

**Issue by ranranJkk** [thunlp/SE-WRL#9]
作者您好！
阅读了SAT.c的代码后，我有个地方不是很明白，希望得到解答，谢谢！
752行的代码，attention[q] += _exp[p] * syn0[target].mult_sense_value[p * layer1_size + q];  请问为什么要有一句呢？这一部分是为了 get "attention" result on senses，但是我感觉存在多个义项的情况里面，之前的代码只使用了meaning_syn去得到每个义项，然后使用attention机制得到一个词的表示，和syn0中的mult_sense_value里面的值没有关系，因此我没有读懂这一句话。请问是我理解有问题吗，如果能指出十分感谢！

**Comment by heyLinsir** [comment]
mult_sense_value是一个义项的表示，根据meaning_syn得到的是每个义项的权重_exp[p]，所以就用那一行代码进行加权平均，不知道我解释到了吗？不是很清楚您的问题。

**Comment by ranranJkk** [comment]
解释到了，原来我是我看错了公式一个地方，跟着就想错了。非常谢谢您的回答！
